package okay.maruko.illagerblabber

import net.minecraft.registry.Registries
import net.minecraft.registry.Registry
import net.minecraft.sound.SoundEvent
import net.minecraft.util.Identifier

object IllagerSounds {

    val SILENCE = registerSound("evoker.silence.01")

    // Ambient noise sounds (1-14)
    val EVOKER_AMBIENT_NOISE_01 = registerSound("evoker.ambient_noise.01")
    val EVOKER_AMBIENT_NOISE_02 = registerSound("evoker.ambient_noise.02")
    val EVOKER_AMBIENT_NOISE_03 = registerSound("evoker.ambient_noise.03")
    val EVOKER_AMBIENT_NOISE_04 = registerSound("evoker.ambient_noise.04")
    val EVOKER_AMBIENT_NOISE_05 = registerSound("evoker.ambient_noise.05")
    val EVOKER_AMBIENT_NOISE_06 = registerSound("evoker.ambient_noise.06")
    val EVOKER_AMBIENT_NOISE_07 = registerSound("evoker.ambient_noise.07")
    val EVOKER_AMBIENT_NOISE_08 = registerSound("evoker.ambient_noise.08")
    val EVOKER_AMBIENT_NOISE_09 = registerSound("evoker.ambient_noise.09")
    val EVOKER_AMBIENT_NOISE_10 = registerSound("evoker.ambient_noise.10")
    val EVOKER_AMBIENT_NOISE_11 = registerSound("evoker.ambient_noise.11")
    val EVOKER_AMBIENT_NOISE_12 = registerSound("evoker.ambient_noise.12")
    val EVOKER_AMBIENT_NOISE_13 = registerSound("evoker.ambient_noise.13")
    val EVOKER_AMBIENT_NOISE_14 = registerSound("evoker.ambient_noise.14")

    // Ambient talk sounds (1-33)
    val EVOKER_AMBIENT_TALK_01 = registerSound("evoker.ambient_talk.01")
    val EVOKER_AMBIENT_TALK_02 = registerSound("evoker.ambient_talk.02")
    val EVOKER_AMBIENT_TALK_03 = registerSound("evoker.ambient_talk.03")
    val EVOKER_AMBIENT_TALK_04 = registerSound("evoker.ambient_talk.04")
    val EVOKER_AMBIENT_TALK_05 = registerSound("evoker.ambient_talk.05")
    val EVOKER_AMBIENT_TALK_06 = registerSound("evoker.ambient_talk.06")
    val EVOKER_AMBIENT_TALK_07 = registerSound("evoker.ambient_talk.07")
    val EVOKER_AMBIENT_TALK_08 = registerSound("evoker.ambient_talk.08")
    val EVOKER_AMBIENT_TALK_09 = registerSound("evoker.ambient_talk.09")
    val EVOKER_AMBIENT_TALK_10 = registerSound("evoker.ambient_talk.10")
    val EVOKER_AMBIENT_TALK_11 = registerSound("evoker.ambient_talk.11")
    val EVOKER_AMBIENT_TALK_12 = registerSound("evoker.ambient_talk.12")
    val EVOKER_AMBIENT_TALK_13 = registerSound("evoker.ambient_talk.13")
    val EVOKER_AMBIENT_TALK_14 = registerSound("evoker.ambient_talk.14")
    val EVOKER_AMBIENT_TALK_15 = registerSound("evoker.ambient_talk.15")
    val EVOKER_AMBIENT_TALK_16 = registerSound("evoker.ambient_talk.16")
    val EVOKER_AMBIENT_TALK_17 = registerSound("evoker.ambient_talk.17")
    val EVOKER_AMBIENT_TALK_18 = registerSound("evoker.ambient_talk.18")
    val EVOKER_AMBIENT_TALK_19 = registerSound("evoker.ambient_talk.19")
    val EVOKER_AMBIENT_TALK_20 = registerSound("evoker.ambient_talk.20")
    val EVOKER_AMBIENT_TALK_21 = registerSound("evoker.ambient_talk.21")
    val EVOKER_AMBIENT_TALK_22 = registerSound("evoker.ambient_talk.22")
    val EVOKER_AMBIENT_TALK_23 = registerSound("evoker.ambient_talk.23")
    val EVOKER_AMBIENT_TALK_24 = registerSound("evoker.ambient_talk.24")
    val EVOKER_AMBIENT_TALK_25 = registerSound("evoker.ambient_talk.25")
    val EVOKER_AMBIENT_TALK_26 = registerSound("evoker.ambient_talk.26")
    val EVOKER_AMBIENT_TALK_27 = registerSound("evoker.ambient_talk.27")
    val EVOKER_AMBIENT_TALK_28 = registerSound("evoker.ambient_talk.28")
    val EVOKER_AMBIENT_TALK_29 = registerSound("evoker.ambient_talk.29")
    val EVOKER_AMBIENT_TALK_30 = registerSound("evoker.ambient_talk.30")
    val EVOKER_AMBIENT_TALK_31 = registerSound("evoker.ambient_talk.31")
    val EVOKER_AMBIENT_TALK_32 = registerSound("evoker.ambient_talk.32")
    val EVOKER_AMBIENT_TALK_33 = registerSound("evoker.ambient_talk.33")

    // Battle sounds (1-14)
    val EVOKER_BATTLE_01 = registerSound("evoker.battle.01")
    val EVOKER_BATTLE_02 = registerSound("evoker.battle.02")
    val EVOKER_BATTLE_03 = registerSound("evoker.battle.03")
    val EVOKER_BATTLE_04 = registerSound("evoker.battle.04")
    val EVOKER_BATTLE_05 = registerSound("evoker.battle.05")
    val EVOKER_BATTLE_06 = registerSound("evoker.battle.06")
    val EVOKER_BATTLE_07 = registerSound("evoker.battle.07")
    val EVOKER_BATTLE_08 = registerSound("evoker.battle.08")
    val EVOKER_BATTLE_09 = registerSound("evoker.battle.09")
    val EVOKER_BATTLE_10 = registerSound("evoker.battle.10")
    val EVOKER_BATTLE_11 = registerSound("evoker.battle.11")
    val EVOKER_BATTLE_12 = registerSound("evoker.battle.12")
    val EVOKER_BATTLE_13 = registerSound("evoker.battle.13")
    val EVOKER_BATTLE_14 = registerSound("evoker.battle.14")

    // Hurt sounds (1-19)
    val EVOKER_HURT_01 = registerSound("evoker.hurt.01")
    val EVOKER_HURT_02 = registerSound("evoker.hurt.02")
    val EVOKER_HURT_03 = registerSound("evoker.hurt.03")
    val EVOKER_HURT_04 = registerSound("evoker.hurt.04")
    val EVOKER_HURT_05 = registerSound("evoker.hurt.05")
    val EVOKER_HURT_06 = registerSound("evoker.hurt.06")
    val EVOKER_HURT_07 = registerSound("evoker.hurt.07")
    val EVOKER_HURT_08 = registerSound("evoker.hurt.08")
    val EVOKER_HURT_09 = registerSound("evoker.hurt.09")
    val EVOKER_HURT_10 = registerSound("evoker.hurt.10")
    val EVOKER_HURT_11 = registerSound("evoker.hurt.11")
    val EVOKER_HURT_12 = registerSound("evoker.hurt.12")
    val EVOKER_HURT_13 = registerSound("evoker.hurt.13")
    val EVOKER_HURT_14 = registerSound("evoker.hurt.14")
    val EVOKER_HURT_15 = registerSound("evoker.hurt.15")
    val EVOKER_HURT_16 = registerSound("evoker.hurt.16")
    val EVOKER_HURT_17 = registerSound("evoker.hurt.17")
    val EVOKER_HURT_18 = registerSound("evoker.hurt.18")
    val EVOKER_HURT_19 = registerSound("evoker.hurt.19")

    // Spotted sounds (1-6)
    val EVOKER_SPOTTED_01 = registerSound("evoker.spotted.01")
    val EVOKER_SPOTTED_02 = registerSound("evoker.spotted.02")
    val EVOKER_SPOTTED_03 = registerSound("evoker.spotted.03")
    val EVOKER_SPOTTED_04 = registerSound("evoker.spotted.04")
    val EVOKER_SPOTTED_05 = registerSound("evoker.spotted.05")
    val EVOKER_SPOTTED_06 = registerSound("evoker.spotted.06")

    // Victory sounds (1-14)
    val EVOKER_VICTORY_01 = registerSound("evoker.victory.01")
    val EVOKER_VICTORY_02 = registerSound("evoker.victory.02")
    val EVOKER_VICTORY_03 = registerSound("evoker.victory.03")
    val EVOKER_VICTORY_04 = registerSound("evoker.victory.04")
    val EVOKER_VICTORY_05 = registerSound("evoker.victory.05")
    val EVOKER_VICTORY_06 = registerSound("evoker.victory.06")
    val EVOKER_VICTORY_07 = registerSound("evoker.victory.07")
    val EVOKER_VICTORY_08 = registerSound("evoker.victory.08")
    val EVOKER_VICTORY_09 = registerSound("evoker.victory.09")
    val EVOKER_VICTORY_10 = registerSound("evoker.victory.10")
    val EVOKER_VICTORY_11 = registerSound("evoker.victory.11")
    val EVOKER_VICTORY_12 = registerSound("evoker.victory.12")
    val EVOKER_VICTORY_13 = registerSound("evoker.victory.13")
    val EVOKER_VICTORY_14 = registerSound("evoker.victory.14")

    private fun registerSound(name: String): SoundEvent {
        val id = Identifier("illagerblabber", name)
        return Registry.register(Registries.SOUND_EVENT, id, SoundEvent.of(id))
    }

    fun registerAll() {
        // This method intentionally left empty
    }

}
